In [122]:
import numpy as np
import scipy.sparse.linalg as sla

In [123]:
tmp = np.array([[0,0,0,0,1],\
                [2,0,0,0,0],\
                [2,2,0,0,0],\
                [2,2,2,0,0],\
                [1,2,2,2,0]])

tmp                

array([[0, 0, 0, 0, 1],
       [2, 0, 0, 0, 0],
       [2, 2, 0, 0, 0],
       [2, 2, 2, 0, 0],
       [1, 2, 2, 2, 0]])

In [124]:
tmp_2 = tmp / tmp.sum(axis=1).reshape(-1,1)
#######
tmp_2 = tmp_2.T
tmp_2 = tmp_2 - np.eye(5)
tmp_2[-1,:] = [1, 1, 1, 1, 1]
np.linalg.solve(tmp_2, np.array([0, 0, 0, 0, 1]))

array([0.30882353, 0.17647059, 0.11764706, 0.08823529, 0.30882353])

In [125]:
'''
Since the sum of each row is 1, our matrix is row stochastic.
We'll transpose the matrix to calculate eigenvectors of the stochastic rows.
'''
transition_matrix_transp = tmp_2.T
eigenvals, eigenvects = np.linalg.eig(transition_matrix_transp)
'''
Find the indexes of the eigenvalues that are close to one.
Use them to select the target eigen vectors. Flatten the result.
'''

close_to_1_idx = np.isclose(eigenvals,1)
target_eigenvect = eigenvects[:,close_to_1_idx]
target_eigenvect = target_eigenvect[:,0]
# Turn the eigenvector elements into probabilites
stationary_distrib = target_eigenvect / sum(target_eigenvect)
stationary_distrib.real

IndexError: index 0 is out of bounds for axis 1 with size 0

In [237]:
finalVoting = np.zeros((40, 40))
finalVoting

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [238]:
for j in range(40):
    #finalVoting[j+1:, j] = [1 + np.sum(range(1,i)) for i in range(1, 40 - j)][::-1]
    #finalVoting[j+1:, j] = [1 + i for i in range(1, 40 - j)][::-1]
    finalVoting[j+1:, j] = [40 /i for i in range(1, 40 - j)]

In [239]:
finalVoting = finalVoting + np.triu(np.ones(40), k = 1)
finalVoting

array([[ 0.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [40.        ,  0.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [20.        , 40.        ,  0.        , ...,  1.        ,
         1.        ,  1.        ],
       ...,
       [ 1.08108108,  1.11111111,  1.14285714, ...,  0.        ,
         1.        ,  1.        ],
       [ 1.05263158,  1.08108108,  1.11111111, ..., 40.        ,
         0.        ,  1.        ],
       [ 1.02564103,  1.05263158,  1.08108108, ..., 20.        ,
        40.        ,  0.        ]])

In [240]:
tmp_2 = finalVoting / finalVoting.sum(axis=1).reshape(-1,1)
#######
tmp_2 = tmp_2.T
tmp_2 = tmp_2 - np.eye(40)
tmp_2[-1,:] = [1 for _ in range(40)]
solution = np.linalg.solve(tmp_2, [0 for _ in range(39)] + [1])
solution

array([0.05754994, 0.04857456, 0.04352251, 0.04016821, 0.03770694,
       0.03578373, 0.03421383, 0.03288989, 0.03174443, 0.03073253,
       0.02982285, 0.0289927 , 0.02822517, 0.02750731, 0.02682893,
       0.02618193, 0.02555966, 0.02495662, 0.02436813, 0.02379018,
       0.02321926, 0.02265219, 0.0220861 , 0.02151828, 0.02094614,
       0.02036714, 0.01977866, 0.01917801, 0.01856222, 0.01792801,
       0.01727155, 0.01658821, 0.0158722 , 0.01511587, 0.01430869,
       0.01343513, 0.01247035, 0.01136984, 0.01003747, 0.00817463])

In [241]:
solution * (90 / solution[0])

array([90.        , 75.96377011, 68.06307737, 62.81742469, 58.96834388,
       55.96071798, 53.50561806, 51.43515052, 49.64382229, 48.06135359,
       46.63873468, 45.34050322, 44.14019888, 43.01755282, 41.95667692,
       40.94485565, 39.97171507, 39.02863516, 38.10832368, 37.20449895,
       36.3116477 , 35.42483434, 34.53954562, 33.65155817, 32.75681954,
       31.85133394, 30.93104424, 29.99170029, 29.02870059, 28.03688867,
       27.01027443, 25.9416313 , 24.82188077, 23.6390966 , 22.37678334,
       21.01064912, 19.50187664, 17.78082529, 15.69718774, 12.78397303])

In [149]:
[0 for _ in range(39)] + [1]

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1]